
name: Packer Validate and Format

 

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

 

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      DEFAULT_SUBNET_ID: ${{ secrets.DEFAULT_SUBNET_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_AMI_USERS: ${{ secrets.AWS_AMI_USERS }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - run: zip -r webapp.zip *
    - run: unzip -l webapp.zip
    - name: Initialize Packer
      run: packer init packer/test.pkr.hcl

    - name: Check Packer Configuration Format
      run: |
        packer fmt  packer/test.pkr.hcl
        if [ $? -ne 0 ]; then
          echo "Packer template format check failed. Please fix the formatting."
          exit 1
        fi
    - name: Validate Packer Configuration
      run: |
        packer validate packer/test.pkr.hcl
        if [ $? -ne 0 ]; then
          echo "Packer template validation failed. Please fix the template."
          exit 1
        fi